version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: blue-example-app
        environment:
            - APP_ENV=dev
            - APP_DEBUG=1
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        networks:
            - blue-example

networks:
    blue-example: